### ISSUE TITLE
Default to UTC if date.timezone is not defined

### ISSUE THREAD

**Issue by jmikola** [jmikola/mongoqp#12]

**Comment by jarvinia** [comment]
Is this issue similar with the one shown as below?
<code>
Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /Users/jun/Dev/mongoqp/vendor/twig/twig/lib/Twig/Extension/Core.php:78 Stack trace: #0 /Users/jun/Dev/mongoqp/vendor/twig/twig/lib/Twig/Extension/Core.php(78): DateTimeZone->__construct('') #1 /Users/jun/Dev/mongoqp/src/app.php(27): Twig_Extension_Core->setTimezone('') #2 /Users/jun/Dev/mongoqp/vendor/pimple/pimple/lib/Pimple.php(201): {closure}(Object(Twig_Environment), Object(Silex\Application)) #3 /Users/jun/Dev/mongoqp/vendor/pimple/pimple/lib/Pimple.php(126): Pimple->{closure}(Object(Silex\Application)) #4 /Users/jun/Dev/mongoqp/vendor/pimple/pimple/lib/Pimple.php(83): Silex\Application::{closure}(Object(Silex\Application)) #5 /Users/jun/Dev/mongoqp/src/app.php(43): Pimple->offsetGet('twig') #6 /Users/jun/Dev/mongoqp/web/index.php(7): require('/Users/jun/Dev/...') #7 {main} thrown in /Users/jun/Dev/mongoqp/vendor/twig/twig/lib/Twig/Extension/Core.php on line 78
</code>

**Comment by jarvinia** [comment]
This issue is resolved when I set the "datetimezone" in php.ini.
